import type { LucideIcon } from "lucide-react";
import {
  Github,
  BookOpen,
  Search,
  MessageSquare,
  Database,
  FolderOpen,
  BarChart3,
  Bug,
  Table2,
  CreditCard,
  Figma,
  ShoppingCart,
  Cloud,
  Leaf,
  Server,
  Zap,
  AlertTriangle,
  GitBranch,
  FileText,
  Users,
  CheckSquare,
  ListTodo,
  Phone,
  Flame,
  Gamepad2,
} from "lucide-react";

// ── Credential field definition ─────────────────────────────

export interface CredentialField {
  key: string;
  label: string;
  type: "text" | "password" | "textarea";
  placeholder?: string;
  hint?: string;
  required: boolean;
}

// ── Tool definition ─────────────────────────────────────────

export interface ToolInfo {
  name: string;
  description: string;
  enabledByDefault: boolean;
}

// ── Template definition ─────────────────────────────────────

export interface TemplateInfo {
  id: string;
  name: string;
  description: string;
  category: "Developer Tools" | "Productivity" | "Search" | "Data" | "Communication";
  icon: LucideIcon;
  toolCount: number;
  comingSoon: boolean;
  credentialFields: CredentialField[];
  credentialHelpUrl: string;
  credentialHelpLabel: string;
  tools: ToolInfo[];
}

export const TEMPLATES: TemplateInfo[] = [
  {
    id: "github",
    name: "GitHub",
    description: "Repos, issues, PRs, and code search",
    category: "Developer Tools",
    icon: Github,
    toolCount: 12,
    comingSoon: false,
    credentialFields: [
      {
        key: "personal_access_token",
        label: "Personal Access Token",
        type: "password",
        placeholder: "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Requires scopes: repo, read:user",
        required: true,
      },
    ],
    credentialHelpUrl: "https://github.com/settings/tokens/new",
    credentialHelpLabel: "Create a GitHub token",
    tools: [
      { name: "list_issues", description: "List issues in a repository", enabledByDefault: true },
      { name: "get_issue", description: "Get a single issue by number", enabledByDefault: true },
      { name: "create_issue", description: "Create a new issue", enabledByDefault: true },
      { name: "update_issue", description: "Update an existing issue", enabledByDefault: true },
      { name: "list_pull_requests", description: "List pull requests", enabledByDefault: true },
      { name: "get_pull_request", description: "Get a single pull request", enabledByDefault: true },
      { name: "list_repositories", description: "List your repositories", enabledByDefault: true },
      { name: "get_repository", description: "Get repository details", enabledByDefault: true },
      { name: "search_issues", description: "Search issues and PRs", enabledByDefault: true },
      { name: "search_code", description: "Search code across repos", enabledByDefault: true },
      { name: "get_file_contents", description: "Read a file from a repo", enabledByDefault: true },
      { name: "push_files", description: "Push files to a repo", enabledByDefault: false },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    description: "Pages, databases, and blocks",
    category: "Productivity",
    icon: BookOpen,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "integration_token",
        label: "Integration Token",
        type: "password",
        placeholder: "ntn_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Create an internal integration in your Notion workspace",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.notion.so/my-integrations",
    credentialHelpLabel: "Create a Notion integration",
    tools: [
      { name: "search", description: "Search pages and databases", enabledByDefault: true },
      { name: "get_page", description: "Get a page by ID", enabledByDefault: true },
      { name: "get_page_content", description: "Get page content blocks", enabledByDefault: true },
      { name: "create_page", description: "Create a new page", enabledByDefault: true },
      { name: "update_page", description: "Update page properties", enabledByDefault: true },
      { name: "query_database", description: "Query a database", enabledByDefault: true },
      { name: "get_database", description: "Get database schema", enabledByDefault: true },
      { name: "create_database_entry", description: "Add a database entry", enabledByDefault: true },
    ],
  },
  {
    id: "brave",
    name: "Brave Search",
    description: "Web and news search",
    category: "Search",
    icon: Search,
    toolCount: 2,
    comingSoon: false,
    credentialFields: [
      {
        key: "api_key",
        label: "API Key",
        type: "password",
        placeholder: "BSA...",
        hint: "Get a free API key from the Brave Search API dashboard",
        required: true,
      },
    ],
    credentialHelpUrl: "https://brave.com/search/api/",
    credentialHelpLabel: "Get a Brave Search API key",
    tools: [
      { name: "web_search", description: "Search the web", enabledByDefault: true },
      { name: "news_search", description: "Search recent news", enabledByDefault: true },
    ],
  },
  {
    id: "slack",
    name: "Slack",
    description: "Messages, channels, and threads",
    category: "Productivity",
    icon: MessageSquare,
    toolCount: 6,
    comingSoon: false,
    credentialFields: [
      {
        key: "bot_token",
        label: "Bot Token",
        type: "password",
        placeholder: "xoxb-...",
        hint: "OAuth scopes: channels:read, chat:write, search:read, users:read",
        required: true,
      },
    ],
    credentialHelpUrl: "https://api.slack.com/apps",
    credentialHelpLabel: "Create a Slack app",
    tools: [
      { name: "list_channels", description: "List workspace channels", enabledByDefault: true },
      { name: "get_channel_history", description: "Get channel messages", enabledByDefault: true },
      { name: "send_message", description: "Send a message to a channel", enabledByDefault: true },
      { name: "search_messages", description: "Search messages", enabledByDefault: true },
      { name: "get_user_info", description: "Get user profile info", enabledByDefault: true },
      { name: "list_users", description: "List workspace members", enabledByDefault: true },
    ],
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Queries, schemas, and analytics",
    category: "Data",
    icon: Database,
    toolCount: 4,
    comingSoon: false,
    credentialFields: [
      {
        key: "connection_string",
        label: "Connection String",
        type: "password",
        placeholder: "postgresql://user:password@host:5432/dbname",
        hint: "Use a read-only user for safety",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING",
    credentialHelpLabel: "Connection string format",
    tools: [
      { name: "query", description: "Execute a SQL query (read-only)", enabledByDefault: true },
      { name: "list_tables", description: "List all tables", enabledByDefault: true },
      { name: "describe_table", description: "Describe a table schema", enabledByDefault: true },
      { name: "list_schemas", description: "List database schemas", enabledByDefault: true },
    ],
  },
  {
    id: "gdrive",
    name: "Google Drive",
    description: "Search, read, and organize files",
    category: "Productivity",
    icon: FolderOpen,
    toolCount: 6,
    comingSoon: true,
    credentialFields: [],
    credentialHelpUrl: "",
    credentialHelpLabel: "",
    tools: [],
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issues, projects, and teams",
    category: "Developer Tools",
    icon: BarChart3,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        placeholder: "lin_api_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Generate a personal API key from Linear Settings → API",
        required: true,
      },
    ],
    credentialHelpUrl: "https://linear.app/settings/api",
    credentialHelpLabel: "Create a Linear API key",
    tools: [
      { name: "list_issues", description: "List issues with optional filters", enabledByDefault: true },
      { name: "get_issue", description: "Get full issue details", enabledByDefault: true },
      { name: "create_issue", description: "Create a new issue", enabledByDefault: true },
      { name: "update_issue", description: "Update an existing issue", enabledByDefault: true },
      { name: "list_teams", description: "List teams and workflow states", enabledByDefault: true },
      { name: "search_issues", description: "Search issues by text", enabledByDefault: true },
      { name: "add_comment", description: "Add a comment to an issue", enabledByDefault: true },
      { name: "list_projects", description: "List projects with progress", enabledByDefault: true },
    ],
  },
  {
    id: "jira",
    name: "Jira",
    description: "Issues, projects, and workflows",
    category: "Developer Tools",
    icon: Bug,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "email",
        label: "Email",
        type: "text",
        placeholder: "you@company.com",
        hint: "The email address for your Atlassian account",
        required: true,
      },
      {
        key: "apiToken",
        label: "API Token",
        type: "password",
        placeholder: "ATATT3x...",
        hint: "Generate from Atlassian account settings",
        required: true,
      },
      {
        key: "domain",
        label: "Jira Domain",
        type: "text",
        placeholder: "your-company.atlassian.net",
        hint: "Your Jira Cloud domain (without https://)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
    credentialHelpLabel: "Create a Jira API token",
    tools: [
      { name: "search_issues", description: "Search issues with JQL", enabledByDefault: true },
      { name: "get_issue", description: "Get full issue details", enabledByDefault: true },
      { name: "create_issue", description: "Create a new issue", enabledByDefault: true },
      { name: "update_issue", description: "Update issue fields", enabledByDefault: true },
      { name: "transition_issue", description: "Change issue status", enabledByDefault: true },
      { name: "add_comment", description: "Comment on an issue", enabledByDefault: true },
      { name: "list_projects", description: "List accessible projects", enabledByDefault: true },
      { name: "get_transitions", description: "Get available transitions", enabledByDefault: true },
    ],
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Bases, tables, and records",
    category: "Data",
    icon: Table2,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "apiKey",
        label: "Personal Access Token",
        type: "password",
        placeholder: "pat...",
        hint: "Create a token with scopes: data.records:read, data.records:write, schema.bases:read",
        required: true,
      },
    ],
    credentialHelpUrl: "https://airtable.com/create/tokens",
    credentialHelpLabel: "Create an Airtable token",
    tools: [
      { name: "list_bases", description: "List accessible bases", enabledByDefault: true },
      { name: "list_tables", description: "List tables in a base", enabledByDefault: true },
      { name: "list_records", description: "List records with filtering", enabledByDefault: true },
      { name: "get_record", description: "Get a single record", enabledByDefault: true },
      { name: "create_records", description: "Create new records", enabledByDefault: true },
      { name: "update_records", description: "Update existing records", enabledByDefault: true },
      { name: "delete_records", description: "Delete records", enabledByDefault: false },
      { name: "search_records", description: "Search records by text", enabledByDefault: true },
    ],
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Customers, charges, subscriptions, and invoices",
    category: "Data",
    icon: CreditCard,
    toolCount: 12,
    comingSoon: false,
    credentialFields: [
      {
        key: "secret_key",
        label: "Secret Key",
        type: "password",
        placeholder: "sk_live_...",
        hint: "Use a restricted key with read-only permissions for safety",
        required: true,
      },
    ],
    credentialHelpUrl: "https://dashboard.stripe.com/apikeys",
    credentialHelpLabel: "Get your Stripe API keys",
    tools: [
      { name: "list_customers", description: "List customers", enabledByDefault: true },
      { name: "get_customer", description: "Get customer details", enabledByDefault: true },
      { name: "create_customer", description: "Create a new customer", enabledByDefault: false },
      { name: "list_charges", description: "List charges", enabledByDefault: true },
      { name: "list_subscriptions", description: "List subscriptions", enabledByDefault: true },
      { name: "get_subscription", description: "Get subscription details", enabledByDefault: true },
      { name: "create_payment_link", description: "Create a payment link", enabledByDefault: false },
      { name: "list_invoices", description: "List invoices", enabledByDefault: true },
      { name: "get_invoice", description: "Get invoice details", enabledByDefault: true },
      { name: "list_products", description: "List products", enabledByDefault: true },
      { name: "get_balance", description: "Get account balance", enabledByDefault: true },
      { name: "search_charges", description: "Search charges", enabledByDefault: true },
    ],
  },
  {
    id: "figma",
    name: "Figma",
    description: "Files, components, styles, and images",
    category: "Developer Tools",
    icon: Figma,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "personal_access_token",
        label: "Personal Access Token",
        type: "password",
        placeholder: "figd_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Generate from Figma Settings > Personal Access Tokens",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.figma.com/developers/api#access-tokens",
    credentialHelpLabel: "Create a Figma access token",
    tools: [
      { name: "get_file", description: "Get a Figma file structure", enabledByDefault: true },
      { name: "get_file_components", description: "List file components", enabledByDefault: true },
      { name: "get_component", description: "Get component metadata", enabledByDefault: true },
      { name: "get_styles", description: "List file styles", enabledByDefault: true },
      { name: "get_team_projects", description: "List team projects", enabledByDefault: true },
      { name: "get_project_files", description: "List project files", enabledByDefault: true },
      { name: "get_images", description: "Export images from a file", enabledByDefault: true },
      { name: "get_variables", description: "Get file variables", enabledByDefault: true },
    ],
  },
  {
    id: "shopify",
    name: "Shopify",
    description: "Products, orders, customers, and inventory",
    category: "Data",
    icon: ShoppingCart,
    toolCount: 10,
    comingSoon: false,
    credentialFields: [
      {
        key: "access_token",
        label: "Admin API Access Token",
        type: "password",
        placeholder: "shpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Create a custom app in your Shopify admin to get an access token",
        required: true,
      },
      {
        key: "store_domain",
        label: "Store Domain",
        type: "text",
        placeholder: "my-store.myshopify.com",
        hint: "Your Shopify store domain (e.g. my-store.myshopify.com)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://help.shopify.com/en/manual/apps/app-types/custom-apps",
    credentialHelpLabel: "Create a Shopify custom app",
    tools: [
      { name: "list_products", description: "List store products", enabledByDefault: true },
      { name: "get_product", description: "Get product details", enabledByDefault: true },
      { name: "list_orders", description: "List store orders", enabledByDefault: true },
      { name: "get_order", description: "Get order details", enabledByDefault: true },
      { name: "list_customers", description: "List store customers", enabledByDefault: true },
      { name: "get_customer", description: "Get customer details", enabledByDefault: true },
      { name: "list_inventory", description: "List inventory levels", enabledByDefault: true },
      { name: "update_inventory", description: "Update inventory quantity", enabledByDefault: false },
      { name: "create_product", description: "Create a new product", enabledByDefault: false },
      { name: "search_orders", description: "Search orders", enabledByDefault: true },
    ],
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Records, queries, reports, and dashboards",
    category: "Data",
    icon: Cloud,
    toolCount: 10,
    comingSoon: false,
    credentialFields: [
      {
        key: "access_token",
        label: "Access Token",
        type: "password",
        placeholder: "00D...",
        hint: "OAuth2 access token from a Connected App",
        required: true,
      },
      {
        key: "instance_url",
        label: "Instance URL",
        type: "text",
        placeholder: "https://na1.salesforce.com",
        hint: "Your Salesforce instance URL (e.g. https://na1.salesforce.com)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://help.salesforce.com/s/articleView?id=sf.connected_app_create.htm",
    credentialHelpLabel: "Create a Salesforce Connected App",
    tools: [
      { name: "query", description: "Execute a SOQL query", enabledByDefault: true },
      { name: "get_record", description: "Get a single record", enabledByDefault: true },
      { name: "create_record", description: "Create a new record", enabledByDefault: false },
      { name: "update_record", description: "Update an existing record", enabledByDefault: false },
      { name: "list_objects", description: "List available object types", enabledByDefault: true },
      { name: "describe_object", description: "Describe object fields", enabledByDefault: true },
      { name: "search", description: "Execute a SOSL search", enabledByDefault: true },
      { name: "list_reports", description: "List available reports", enabledByDefault: true },
      { name: "get_report", description: "Run a report", enabledByDefault: true },
      { name: "list_dashboards", description: "List dashboards", enabledByDefault: true },
    ],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Documents, collections, and aggregations",
    category: "Data",
    icon: Leaf,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "api_key",
        label: "Data API Key",
        type: "password",
        placeholder: "your-data-api-key",
        hint: "Generate a Data API key from the MongoDB Atlas UI",
        required: true,
      },
      {
        key: "app_id",
        label: "App ID",
        type: "text",
        placeholder: "data-xxxxx",
        hint: "Your Atlas App Services app ID",
        required: true,
      },
      {
        key: "cluster_name",
        label: "Cluster Name",
        type: "text",
        placeholder: "Cluster0",
        hint: "The name of your MongoDB Atlas cluster",
        required: true,
      },
      {
        key: "database_name",
        label: "Database Name",
        type: "text",
        placeholder: "mydb",
        hint: "Default database to use for queries",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.mongodb.com/docs/atlas/app-services/data-api/",
    credentialHelpLabel: "Set up MongoDB Data API",
    tools: [
      { name: "list_databases", description: "List all databases", enabledByDefault: true },
      { name: "list_collections", description: "List collections in a database", enabledByDefault: true },
      { name: "find_documents", description: "Find documents with filters", enabledByDefault: true },
      { name: "insert_document", description: "Insert a document", enabledByDefault: true },
      { name: "update_documents", description: "Update matching documents", enabledByDefault: true },
      { name: "delete_documents", description: "Delete matching documents", enabledByDefault: false },
      { name: "aggregate", description: "Run an aggregation pipeline", enabledByDefault: true },
      { name: "create_index", description: "Create a collection index", enabledByDefault: false },
    ],
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Queries, tables, and schemas via HTTP proxy",
    category: "Data",
    icon: Server,
    toolCount: 4,
    comingSoon: false,
    credentialFields: [
      {
        key: "api_endpoint",
        label: "HTTP Proxy Endpoint",
        type: "password",
        placeholder: "https://your-mysql-proxy.fly.dev/query",
        hint: "URL of a MySQL HTTP proxy (e.g. PlanetScale Serverless, or a self-hosted proxy on Fly.io)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://planetscale.com/docs/tutorials/connect-any-application",
    credentialHelpLabel: "MySQL HTTP proxy setup",
    tools: [
      { name: "query", description: "Execute a SQL query (read-only)", enabledByDefault: true },
      { name: "list_tables", description: "List all tables", enabledByDefault: true },
      { name: "describe_table", description: "Describe a table schema", enabledByDefault: true },
      { name: "list_schemas", description: "List database schemas", enabledByDefault: true },
    ],
  },
  {
    id: "redis",
    name: "Redis",
    description: "Keys, hashes, lists, and scans",
    category: "Data",
    icon: Zap,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "rest_url",
        label: "REST URL",
        type: "text",
        placeholder: "https://us1-xxxxx.upstash.io",
        hint: "Your Upstash Redis REST URL",
        required: true,
      },
      {
        key: "rest_token",
        label: "REST Token",
        type: "password",
        placeholder: "AXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Your Upstash Redis REST token",
        required: true,
      },
    ],
    credentialHelpUrl: "https://upstash.com/docs/redis/overall/getstarted",
    credentialHelpLabel: "Create an Upstash Redis database",
    tools: [
      { name: "get", description: "Get a key value", enabledByDefault: true },
      { name: "set", description: "Set a key value", enabledByDefault: true },
      { name: "delete", description: "Delete keys", enabledByDefault: true },
      { name: "list_keys", description: "Scan for keys by pattern", enabledByDefault: true },
      { name: "hget", description: "Get a hash field", enabledByDefault: true },
      { name: "hset", description: "Set hash fields", enabledByDefault: true },
      { name: "lpush", description: "Prepend to a list", enabledByDefault: true },
      { name: "lrange", description: "Get list elements", enabledByDefault: true },
    ],
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking, issues, and releases",
    category: "Developer Tools",
    icon: AlertTriangle,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "auth_token",
        label: "Auth Token",
        type: "password",
        placeholder: "sntrys_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Create an auth token with project:read, org:read, and event:read scopes",
        required: true,
      },
      {
        key: "organization_slug",
        label: "Organization Slug",
        type: "text",
        placeholder: "my-org",
        hint: "Your Sentry organization slug (from the URL)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://sentry.io/settings/account/api/auth-tokens/",
    credentialHelpLabel: "Create a Sentry auth token",
    tools: [
      { name: "list_issues", description: "List issues for a project", enabledByDefault: true },
      { name: "get_issue", description: "Get full issue details", enabledByDefault: true },
      { name: "list_events", description: "List events for an issue", enabledByDefault: true },
      { name: "resolve_issue", description: "Resolve or unresolve an issue", enabledByDefault: true },
      { name: "list_projects", description: "List organization projects", enabledByDefault: true },
      { name: "get_event", description: "Get full event details", enabledByDefault: true },
      { name: "search_issues", description: "Search issues across projects", enabledByDefault: true },
      { name: "list_releases", description: "List releases", enabledByDefault: true },
    ],
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Projects, MRs, issues, and CI/CD pipelines",
    category: "Developer Tools",
    icon: GitBranch,
    toolCount: 10,
    comingSoon: false,
    credentialFields: [
      {
        key: "personal_access_token",
        label: "Personal Access Token",
        type: "password",
        placeholder: "glpat-xxxxxxxxxxxxxxxxxxxx",
        hint: "Create a token with api or read_api scope",
        required: true,
      },
      {
        key: "instance_url",
        label: "Instance URL",
        type: "text",
        placeholder: "https://gitlab.com",
        hint: "Your GitLab instance URL (leave blank for gitlab.com)",
        required: false,
      },
    ],
    credentialHelpUrl: "https://gitlab.com/-/user_settings/personal_access_tokens",
    credentialHelpLabel: "Create a GitLab token",
    tools: [
      { name: "list_projects", description: "List accessible projects", enabledByDefault: true },
      { name: "get_project", description: "Get project details", enabledByDefault: true },
      { name: "list_merge_requests", description: "List merge requests", enabledByDefault: true },
      { name: "get_merge_request", description: "Get merge request details", enabledByDefault: true },
      { name: "list_issues", description: "List project issues", enabledByDefault: true },
      { name: "create_issue", description: "Create a new issue", enabledByDefault: true },
      { name: "list_pipelines", description: "List CI/CD pipelines", enabledByDefault: true },
      { name: "get_pipeline", description: "Get pipeline details", enabledByDefault: true },
      { name: "search_code", description: "Search code across projects", enabledByDefault: true },
      { name: "get_file", description: "Get file contents from a repo", enabledByDefault: true },
    ],
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Pages, spaces, and content search",
    category: "Productivity",
    icon: FileText,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "email",
        label: "Email",
        type: "text",
        placeholder: "you@company.com",
        hint: "The email address for your Atlassian account",
        required: true,
      },
      {
        key: "api_token",
        label: "API Token",
        type: "password",
        placeholder: "ATATT3x...",
        hint: "Generate from Atlassian account settings",
        required: true,
      },
      {
        key: "domain",
        label: "Confluence Domain",
        type: "text",
        placeholder: "your-company",
        hint: "Your Atlassian site name (the part before .atlassian.net)",
        required: true,
      },
    ],
    credentialHelpUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
    credentialHelpLabel: "Create an Atlassian API token",
    tools: [
      { name: "search_content", description: "Search content with CQL", enabledByDefault: true },
      { name: "get_page", description: "Get a page by ID", enabledByDefault: true },
      { name: "create_page", description: "Create a new page", enabledByDefault: true },
      { name: "update_page", description: "Update an existing page", enabledByDefault: true },
      { name: "list_spaces", description: "List accessible spaces", enabledByDefault: true },
      { name: "get_space", description: "Get space details", enabledByDefault: true },
      { name: "get_page_children", description: "Get child pages", enabledByDefault: true },
      { name: "add_comment", description: "Add a comment to a page", enabledByDefault: true },
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Contacts, deals, companies, and tickets",
    category: "Data",
    icon: Users,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "access_token",
        label: "Private App Access Token",
        type: "password",
        placeholder: "pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        hint: "Create a private app in HubSpot with CRM scopes",
        required: true,
      },
    ],
    credentialHelpUrl: "https://developers.hubspot.com/docs/api/private-apps",
    credentialHelpLabel: "Create a HubSpot private app",
    tools: [
      { name: "list_contacts", description: "List CRM contacts", enabledByDefault: true },
      { name: "get_contact", description: "Get contact details", enabledByDefault: true },
      { name: "create_contact", description: "Create a new contact", enabledByDefault: true },
      { name: "list_deals", description: "List deals", enabledByDefault: true },
      { name: "get_deal", description: "Get deal details", enabledByDefault: true },
      { name: "list_companies", description: "List companies", enabledByDefault: true },
      { name: "search_contacts", description: "Search contacts", enabledByDefault: true },
      { name: "list_tickets", description: "List support tickets", enabledByDefault: true },
    ],
  },
  {
    id: "asana",
    name: "Asana",
    description: "Tasks, projects, and team collaboration",
    category: "Productivity",
    icon: CheckSquare,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "personal_access_token",
        label: "Personal Access Token",
        type: "password",
        placeholder: "1/1234567890:abcdef...",
        hint: "Generate from Asana Developer Console under Personal access tokens",
        required: true,
      },
    ],
    credentialHelpUrl: "https://app.asana.com/0/developer-console",
    credentialHelpLabel: "Create an Asana token",
    tools: [
      { name: "list_tasks", description: "List tasks in a project", enabledByDefault: true },
      { name: "get_task", description: "Get full task details", enabledByDefault: true },
      { name: "create_task", description: "Create a new task", enabledByDefault: true },
      { name: "update_task", description: "Update an existing task", enabledByDefault: true },
      { name: "list_projects", description: "List workspace projects", enabledByDefault: true },
      { name: "get_project", description: "Get project details", enabledByDefault: true },
      { name: "search_tasks", description: "Search tasks in a workspace", enabledByDefault: true },
      { name: "add_comment", description: "Add a comment to a task", enabledByDefault: true },
    ],
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Tasks, projects, and personal productivity",
    category: "Productivity",
    icon: ListTodo,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "api_token",
        label: "API Token",
        type: "password",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Find your API token in Todoist Settings → Integrations → Developer",
        required: true,
      },
    ],
    credentialHelpUrl: "https://todoist.com/help/articles/find-your-api-token-Jpzx9IIlB",
    credentialHelpLabel: "Find your Todoist API token",
    tools: [
      { name: "list_tasks", description: "List active tasks with filters", enabledByDefault: true },
      { name: "get_task", description: "Get full task details", enabledByDefault: true },
      { name: "create_task", description: "Create a new task", enabledByDefault: true },
      { name: "update_task", description: "Update an existing task", enabledByDefault: true },
      { name: "complete_task", description: "Mark a task as completed", enabledByDefault: true },
      { name: "list_projects", description: "List all projects", enabledByDefault: true },
      { name: "create_project", description: "Create a new project", enabledByDefault: true },
      { name: "add_comment", description: "Add a comment to a task", enabledByDefault: true },
    ],
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, voice calls, and phone number management",
    category: "Communication",
    icon: Phone,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "account_sid",
        label: "Account SID",
        type: "text",
        placeholder: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Found on your Twilio Console dashboard",
        required: true,
      },
      {
        key: "auth_token",
        label: "Auth Token",
        type: "password",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Found on your Twilio Console dashboard",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.twilio.com/docs/iam/keys/api-key",
    credentialHelpLabel: "Find your Twilio credentials",
    tools: [
      { name: "send_sms", description: "Send an SMS message", enabledByDefault: true },
      { name: "list_messages", description: "List SMS/MMS messages", enabledByDefault: true },
      { name: "get_message", description: "Get message details", enabledByDefault: true },
      { name: "make_call", description: "Initiate a phone call", enabledByDefault: false },
      { name: "list_calls", description: "List phone calls", enabledByDefault: true },
      { name: "get_call", description: "Get call details", enabledByDefault: true },
      { name: "list_phone_numbers", description: "List owned phone numbers", enabledByDefault: true },
      { name: "lookup_number", description: "Look up phone number info", enabledByDefault: true },
    ],
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    description: "Web scraping, crawling, and data extraction",
    category: "Search",
    icon: Flame,
    toolCount: 6,
    comingSoon: false,
    credentialFields: [
      {
        key: "api_key",
        label: "API Key",
        type: "password",
        placeholder: "fc-xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Get an API key from the Firecrawl dashboard",
        required: true,
      },
    ],
    credentialHelpUrl: "https://www.firecrawl.dev/app/api-keys",
    credentialHelpLabel: "Get a Firecrawl API key",
    tools: [
      { name: "scrape_url", description: "Scrape a single URL", enabledByDefault: true },
      { name: "crawl_site", description: "Crawl an entire website", enabledByDefault: true },
      { name: "search_web", description: "Search the web with scraping", enabledByDefault: true },
      { name: "extract_data", description: "Extract structured data from URLs", enabledByDefault: true },
      { name: "get_crawl_status", description: "Check crawl job status", enabledByDefault: true },
      { name: "map_site", description: "Map all URLs on a site", enabledByDefault: true },
    ],
  },
  {
    id: "discord",
    name: "Discord",
    description: "Guilds, channels, messages, and members",
    category: "Communication",
    icon: Gamepad2,
    toolCount: 8,
    comingSoon: false,
    credentialFields: [
      {
        key: "bot_token",
        label: "Bot Token",
        type: "password",
        placeholder: "MTxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Create a bot in the Discord Developer Portal and copy its token",
        required: true,
      },
    ],
    credentialHelpUrl: "https://discord.com/developers/applications",
    credentialHelpLabel: "Create a Discord bot",
    tools: [
      { name: "list_guilds", description: "List bot's guilds (servers)", enabledByDefault: true },
      { name: "list_channels", description: "List channels in a guild", enabledByDefault: true },
      { name: "get_channel_messages", description: "Get channel messages", enabledByDefault: true },
      { name: "send_message", description: "Send a message to a channel", enabledByDefault: true },
      { name: "list_members", description: "List guild members", enabledByDefault: true },
      { name: "get_user", description: "Get user information", enabledByDefault: true },
      { name: "create_channel", description: "Create a new channel", enabledByDefault: false },
      { name: "search_messages", description: "Search messages in a guild", enabledByDefault: true },
    ],
  },
];

export const CATEGORIES = [
  "All",
  "Developer Tools",
  "Productivity",
  "Search",
  "Data",
  "Communication",
] as const;
